force-app/main/default/objects/Agent_Event__e/Agent_Event__e.object-meta.xml
<CustomObject>
    <description>Publishes Immediately as soon as:

- Agent is sent a message
- Agent responds
- Agent Action is run</description>
    <label>Agent Event</label>
    <pluralLabel>Agent Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Agent_Event__e/fields/Agent_Id__c.field-meta.xml
<CustomField>
    <fullName>Agent_Id__c</fullName>
    <description>The ID of the agent this event corresponds to</description>
    <label>Agent Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Agent_Event__e/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <description>State about this event</description>
    <label>Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Agent_Event__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The event type. See Agent.EventTypes enum</description>
    <inlineHelpText>The event type. See Agent.EventTypes enum</inlineHelpText>
    <label>Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/observability/objects/Agent_Log__c/Agent_Log__c.object-meta.xml
<CustomObject>
    <description>Logs of LLM Agents</description>
    <label>Agent Log</label>
    <nameField>
        <label>Agent Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agent Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/observability/objects/Agent_Log__c/fields/Agent_Id__c.field-meta.xml
<CustomField>
    <fullName>Agent_Id__c</fullName>
    <description>Unique ID of agent</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique ID of agent</inlineHelpText>
    <label>Agent Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/observability/objects/Agent_Log__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <description>Error message if agent failed</description>
    <inlineHelpText>Error message if agent failed</inlineHelpText>
    <label>Error</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/observability/objects/Agent_Log__c/fields/Events__c.field-meta.xml
<CustomField>
    <fullName>Events__c</fullName>
    <description>JSON serialized list of events</description>
    <label>Events</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/observability/objects/Agent_Log__c/fields/Input__c.field-meta.xml
<CustomField>
    <fullName>Input__c</fullName>
    <description>The objective or user input to the agent</description>
    <label>Input</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Agent_Log__c/fields/Last_Agent_Update__c.field-meta.xml
<CustomField>
    <fullName>Last_Agent_Update__c</fullName>
    <description>The last time the agent ran</description>
    <inlineHelpText>The last time the agent ran</inlineHelpText>
    <label>Last Agent Update</label>
    <type>DateTime</type>
</CustomField>

force-app/main/observability/objects/Agent_Log__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <description>The result of the invocation</description>
    <inlineHelpText>The result of the invocation</inlineHelpText>
    <label>Result</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Agent_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;In Progress&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AgentEventHandler.cls
/** Takes PE and updates log */
public with sharing class AgentEventHandler {
  public void handle() {
    Map<String, Agent_Event__e[]> eventsByAgentId = new Map<String, Agent_Event__e[]>();
    for (Agent_Event__e evt : (Agent_Event__e[]) Trigger.new) {
      //these are just used to trigger the UI update ASAP
      if (evt.Type__c == Agent.EventType.LOG_INIT.name()) {
        continue;
      }
      if (!eventsByAgentId.containsKey(evt.Agent_Id__c)) {
        eventsByAgentId.put(evt.Agent_Id__c, new List<Agent_Event__e>{ evt });
      } else {
        eventsByAgentId.get(evt.Agent_Id__c).add(evt);
      }
    }

    Agent_Log__c[] logs = [
      SELECT Agent_Id__c, Events__c
      FROM Agent_Log__c
      WHERE Agent_Id__c IN :eventsByAgentId.keySet()
    ];

    Map<String, Agent_Log__c> logsByAgentId = new Map<String, Agent_Log__c>();
    for (Agent_Log__c log : logs) {
      logsByAgentId.put(log.Agent_Id__c, log);
    }
    Agent_Log__c[] logsToUpsert = new List<Agent_Log__c>{};
    for (String agentId : eventsByAgentId.keySet()) {
      Agent_Log__c log = logsByAgentId.get(agentId);

      if (log == null) {
        log = new Agent_Log__c();
        log.Agent_Id__c = agentId;
      }
      AgentEventLog[] events = new List<AgentEventLog>{};

      if (log.Events__c != null) {
        try {
          events = (AgentEventLog[]) JSON.deserialize(
            log.Events__c,
            List<AgentEventLog>.class
          );
        } catch (Exception e) {
          System.debug('failed to deserialize events');
          System.debug(e);
        }
      }

      for (Agent_Event__e newEvent : eventsByAgentId.get(agentId)) {
        events.add(new AgentEventLog(newEvent));

        if (newEvent.Type__c == Agent.EventType.AGENT_CREATED.name()) {
          log.Input__c = newEvent.Data__c;
          log.Status__c = 'In Progress';
        } else if (newEvent.Type__c == Agent.EventType.AGENT_COMPLETED.name()) {
          log.Result__c = newEvent.Data__c;
          log.Status__c = 'Completed';
        } else if (newEvent.Type__c == Agent.EventType.AGENT_CRASH.name()) {
          log.Error__c = newEvent.Data__c;
          log.Status__c = 'Error';
        }
        log.Last_Agent_Update__c = newEvent.CreatedDate;
      }

      log.Events__c = JSON.serialize(events);

      logsToUpsert.add(log);
    }
    upsert logsToUpsert Agent_Id__c;
  }

  public class AgentEventLog {
    public string eventType;
    public string data;
    public DateTime timestamp;

    public AgentEventLog() {
    }
    public AgentEventLog(Agent_Event__e evt) {
      this.eventType = evt.Type__c;
      this.data = evt.Data__c;
      this.timestamp = evt.CreatedDate;
    }
  }
}