force-app/main/default/objects/Agent_Event__e/Agent_Event__e.object-meta.xml
<CustomObject>
    <description>Publishes Immediately as soon as:

- Agent is sent a message
- Agent responds
- Agent Action is run</description>
    <label>Agent Event</label>
    <pluralLabel>Agent Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Agent_Event__e/fields/Agent_Id__c.field-meta.xml
<CustomField>
    <fullName>Agent_Id__c</fullName>
    <description>The ID of the agent this event corresponds to</description>
    <label>Agent Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Agent_Event__e/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <description>State about this event</description>
    <label>Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/observability/objects/Agent_Event__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The event type. See Agent.EventTypes enum</description>
    <label>Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/observability/classes/AgentEventProducer.cls
public class AgentEventProducer implements Agent.EventHandler {
  public void publish(String agentId, string type, Object data) {
    List<Agent_Event__e> agentLogEvents = new List<Agent_Event__e>();
    agentLogEvents.add(
      new Agent_Event__e(
        Agent_Id__c = agentId,
        Type__c = type,
        Data__c = JSON.serialize(data)
      )
    );
    EventBus.publish(agentLogEvents);
  }

  public void onEvent(String agentId, Agent.EventType type, Object data) {
    publish(agentId, type.name(), data);
  }
}